# mysql 실행: docker compose up -d
# mysql 접속: docker exec -it gomoku-mysql mysql -u admin -p

version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: gomoku-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gomoku
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: