name: Train Model Pipeline

on:
  workflow_dispatch:  # 수동 실행 트리거
  # schedule:
  #   - cron: '0 0 * * *'  # (옵션) 매일 자정에 자동 실행되도록 설정하려면 주석 해제

jobs:
  train:
    # GPU가 설정된 러너가 있다면 이 부분을 바꿔주세요.
    # runs-on: [self-hosted, gpu, linux]
    # 또는 GitHub 제공 GPU 러너를 쓰는 경우 (Enterprise 플랜 필요)
    # runs-on: ubuntu-20.04-gpu-4core
    runs-on: ubuntu-latest  # 기본 CPU 환경

    timeout-minutes: 120  # 학습 시간 제한

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 사용하는 파이썬 버전으로 수정

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Extract Data
        run: python mlops/data/extract_data.py  # 데이터 추출 스크립트명으로 변경

      - name: Prepare Training Data
        run: python training/make_train_data.py  # 데이터 전처리/생성 스크립트명으로 변경

      - name: Train Model
        run: python training/fine_tuning.py  # 파인튜닝 또는 학습 스크립트명으로 변경

      - name: Upload model artifact
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: path/to/saved/model.pt  # 저장된 모델 경로로 변경
