name: Train Model Pipeline

on:
  schedule:
    - cron: '20 20 * * 6'  # 매주 일요일 05:00 KST (UTC+9)
  workflow_dispatch:       # 수동 실행 가능 추가

jobs:
  train:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r mlops/requirements.txt

      - name: Prepare Training Data
        run: python mlops/training/make_train_data.py

      - name: Train Model
        run: python mlops/training/fine_tuning.py

      - name: Commit and push trained model to repository
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          git pull origin main
          git add mlops/training/models/
          git commit -m "Add fine-tuned model automatically [CI]" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
