name: Train Model Pipeline

on:
  schedule:
    - cron: '30 1 * * 2'  # 매주 화요일 10:30 KST (UTC+9)
jobs:
  train:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r mlops/requirements.txt

      # 데이터 추출은 리눅스 서버에서 별도로 실행하므로 생략

      - name: Prepare Training Data
        run: python mlops/training/make_train_data.py

      - name: Train Model
        run: python mlops/training/fine_tuning.py

      # - name: Upload model artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: trained-model
      #     path: training/models/model_best.pt